# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6fe8b0bc0888f99f7ab2c1bbdeb91be248db4351a275ca54ec846c0541dece3ca346205beb79dbe1bf9cfe978079667fd7d93061faac00d2f20b0db0ecdcaa95

test:
  secret_key_base: 9717a211a799655530e4acb1361cc4d2d9bb191c5d6c5f53634c9352991d63f56c707337aed83e24e2c317c04ad956b7e53c3e930c5dc97922f802a824eb7aa8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
